version: "3.3"
services:

  db:
    restart: always
    container_name: postgres_container
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgresDB
      POSTGRES_PASSWORD: 2008
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin4:
      image: elestio/pgadmin:latest
      container_name: pgadmin4_container
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: danilsmor@mail.ru
        PGADMIN_DEFAULT_PASSWORD: 2008
        PGADMIN_LISTEN_PORT: 8080
      ports:
      - "8080:8080"
      volumes:
      - ./servers.json:/pgadmin4/servers.json