version: '3.6'

services:
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: dan
        MONGO_INITDB_ROOT_PASSWORD: 2008
      ports:
        - 27017:27017
      volumes:
        - type: bind
          source: ./data
          target: /data/db


    mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: dan
        ME_CONFIG_MONGODB_ADMINPASSWORD: 2008
        ME_CONFIG_MONGODB_URL: mongodb://dan:2008@mongo:27017/
        ME_CONFIG_BASICAUTH: false